---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zytest-kafka-1
  labels:
    name: zytest-kafka-1
    broker_id: "6"
spec:
  replicas: 1
  selector:
    name: zytest-kafka-1
    broker_id: "6"
  template:
    metadata:
      labels:
        name: zytest-kafka-1
        broker_id: "6"
        service: zytest-kafka
    spec:
      containers:
        - name: kafka
          image: zzyin/kafka:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "6"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "zytest-kafka-1"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
            - name: NEW_RELIC_ENABLED
              value: "true"
            - name: JMX_PORT
              value: "9999"
            - name: APP_NAME
              value: "BITS Test Kafka"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data

