---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-1
  labels:
    name: kafka-1
    broker_id: "1"
spec:
  replicas: 1
  selector:
    name: kafka-1
    broker_id: "1"
  template:
    metadata:
      labels:
        name: kafka-1
        broker_id: "1"
        service: kafka
    spec:
      containers:
        - name: kafka
          image: navicore/kafka:0.10.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "1"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-1"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-2
  labels:
    name: kafka-2
    broker_id: "2"
spec:
  replicas: 1
  selector:
    name: kafka-2
    broker_id: "2"
  template:
    metadata:
      labels:
        name: kafka-2
        broker_id: "2"
        service: kafka
    spec:
      containers:
        - name: kafka
          image: navicore/kafka:0.10.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "2"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-2"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-3
  labels:
    name: kafka-3
    broker_id: "3"
spec:
  replicas: 1
  selector:
    name: kafka-3
    broker_id: "3"
  template:
    metadata:
      labels:
        name: kafka-3
        broker_id: "3"
        service: kafka
    spec:
      containers:
        - name: kafka
          image: navicore/kafka:0.10.1.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "750Mi"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "3"
            - name: NUM_PARTITIONS
              value: "3"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-3"
            - name: ZOOKEEPER_CONNECT
              value: "zoo1:2181,zoo2:2181,zoo3:2181"
            - name: RETENTION_HOURS
              value: "72"
          ports:
            - containerPort: 9092
              name: broker
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - emptyDir: {}
          name: data

