---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka
    service: kafka
spec:
  ports:
    - name: broker
      port: 9092
  selector:
    service: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    name: kafka-1
    service: kafka
    broker_id: "1"
spec:
  ports:
    - name: broker
      port: 9092
  selector:
    name: kafka-1
    broker_id: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    name: kafka-2
    service: kafka
    broker_id: "2"
spec:
  ports:
    - name: broker
      port: 9092
  selector:
    name: kafka-2
    broker_id: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3
  labels:
    name: kafka-3
    service: kafka
    broker_id: "3"
spec:
  ports:
    - name: broker
      port: 9092
  selector:
    name: kafka-3
    broker_id: "3"

